### ISSUE TITLE
Some recipes are broken when Paradise Lost is installed

### ISSUE THREAD

**Issue by goldenapple3** [RealRTTV/malum-fabric#9]
Mmm, more recipe weirdness

Paradise Lost includes a dependency called Recipe Confidence to force, say, this recipe to produce specifically a Skyroot Chest and not a generic wooden Chest:
![image](https://user-images.githubusercontent.com/53568168/174459773-60a9fbca-91ec-4350-a49f-6ad30a563f1d.png)

However, as you can see, that recipe is broken when Malum is installed. Also the crafting interface can glitch out a bit and sometimes it can either duplicate or void the ingredients.

I can still craft a standard Chest by including some generic wood though:
![image](https://user-images.githubusercontent.com/53568168/174459782-0997e666-68a1-4a0a-bc59-e530b9793ae2.png)

And I *can* craft a Skyroot Chest if Malum is removed.

```
malum-quilt-b1.0.6.jar
paradise-lost-1.6.8+1.18.2.jar
qsl-1.1.0-beta.19_qfapi-1.0.0-beta.22_fapi-0.56.0_mc-1.18.2.jar
```
Full log is here: [latest.log](https://github.com/RealRTTV/malum-fabric/files/8934494/latest.log)
What I think is the relevant part is here:
```
[02:10:12] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2813@4b1ba0a2, suppressing error
net.minecraft.class_148: Container click
	at net.minecraft.class_1703.method_7593(class_1703.java:305) ~[client-intermediary.jar:?]
	at net.minecraft.class_3244.method_12076(class_3244.java:1436) ~[client-intermediary.jar:?]
	at net.minecraft.class_2813.method_12191(class_2813.java:58) ~[client-intermediary.jar:?]
	at net.minecraft.class_2813.method_11054(class_2813.java:13) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3738.run(class_3738.java:18) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:769) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassCastException: class net.minecraft.class_1856 cannot be cast to class net.gudenau.minecraft.recipeconfidence.duck.IngredientDuck (net.minecraft.class_1856 and net.gudenau.minecraft.recipeconfidence.duck.IngredientDuck are in unnamed module of loader org.quiltmc.loader.impl.launch.knot.KnotClassLoader @2b0f373b)
	at net.minecraft.class_1860.gud_recipe_confidence$getConfidence(class_1860.java:522) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.mdadf9fb$lambda$getFirstMatch$0$0(class_1863.java:524) ~[client-intermediary.jar:?]
	at java.util.function.BinaryOperator.lambda$minBy$0(BinaryOperator.java:59) ~[?:?]
	at java.util.stream.ReduceOps$2ReducingSink.accept(ReduceOps.java:123) ~[?:?]
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411) ~[?:?]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762) ~[?:?]
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276) ~[?:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueSpliterator.acceptOnIndex(Object2ObjectOpenHashMap.java:1195) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueSpliterator.acceptOnIndex(Object2ObjectOpenHashMap.java:1179) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$MapSpliterator.forEachRemaining(Object2ObjectOpenHashMap.java:857) ~[fastutil-8.5.6.jar:?]
	at it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap$ValueSpliterator.forEachRemaining(Object2ObjectOpenHashMap.java:1179) ~[fastutil-8.5.6.jar:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:662) ~[?:?]
	at java.util.stream.ReferencePipeline.min(ReferencePipeline.java:703) ~[?:?]
	at net.minecraft.class_1863.redirect$zdk000$getFirstMatch(class_1863.java:523) ~[client-intermediary.jar:?]
	at net.minecraft.class_1863.method_8132(class_1863.java:72) ~[client-intermediary.jar:?]
	at net.minecraft.class_1714.method_17399(class_1714.java:66) ~[client-intermediary.jar:?]
	at net.minecraft.class_1714.method_17401(class_1714.java:81) ~[client-intermediary.jar:?]
	at net.minecraft.class_3914.method_17394(class_3914.java:35) ~[client-intermediary.jar:?]
	at net.minecraft.class_3914$2.method_17395(class_3914.java:22) ~[client-intermediary.jar:?]
	at net.minecraft.class_3914.method_17393(class_3914.java:34) ~[client-intermediary.jar:?]
	at net.minecraft.class_1714.method_7609(class_1714.java:81) ~[client-intermediary.jar:?]
	at net.minecraft.class_1715.method_5447(class_1715.java:63) ~[client-intermediary.jar:?]
	at net.minecraft.class_1735.method_7673(class_1735.java:61) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_30010(class_1703.java:362) ~[client-intermediary.jar:?]
	at net.minecraft.class_1703.method_7593(class_1703.java:295) ~[client-intermediary.jar:?]
	... 17 more
```

**Comment by RealRTTV** [comment]
custom classloader stuff, goddamnit

**Comment by RealRTTV** [comment]
not classloader, duck interface

**Comment by RealRTTV** [comment]
from what i see, loading recipes seemed to fail drastically since someone made an ingredient duck, and it seems to be screaming

**Comment by RealRTTV** [comment]
since for some reason it doesn't apply

**Comment by RealRTTV** [comment]
why do an @Unique on an @Override

**Comment by goldenapple3** [comment]
Unlike with #8, most recipes do work and show up in REI, just a few of these "confidence" recipes fail

**Comment by RealRTTV** [comment]
yea, from what i see

**Comment by goldenapple3** [comment]
Also I honestly don't know if this is worth investigating, I wanted to post this to the Paradise Lost repo too but their issue template suggests that they just don't want to support Quilt

**Comment by RealRTTV** [comment]
an `@Unique` annotation, modifies a method name to be a random hash thing if conflicts happen, if you do that on an `@Override` it won't override the method anymore, but that's not what's happening, for some reason the mixin is failing to make Ingredient implement IngredientDuck

**Comment by RealRTTV** [comment]
i think i may be able to fix it on my end, or I may not, my classes or mixins aren't mentioned in the stacktrace

**Comment by RealRTTV** [comment]
im gonna try to recreate it, then mess around a lot

**Comment by RealRTTV** [comment]
currently we're developing 1.19, but we should've made a separate branch, @Arathain

**Comment by goldenapple3** [comment]
(I know Java but don't know Minecraft modding) Yeah, from what I can tell, Malum does not do anything super special with recipes, but this and the other recipe issue from earlier only happen with Malum in a modpack with 150+ jars, so I dunno

**Comment by goldenapple3** [comment]
> currently we're developing 1.19, but we should've made a separate branch, @Arathain

Never to late to make a separate branch from an earlier commit, I guess

**Comment by RealRTTV** [comment]
yea true, i can't recreate it for some reason

**Comment by RealRTTV** [comment]
can you make any other recipes?

**Comment by goldenapple3** [comment]
I'm booting it up again with a slightly newer version of PL, I submitted this issue with 1.6.8 which is the latest on Modrinth but the latest on Curse is 1.6.9...

**Comment by RealRTTV** [comment]
i think my accesswidening may be causing issues

**Comment by goldenapple3** [comment]
Nope, issue with the chest still happens, tried a bunch of other recipes and those work fine.

In my bigger modpack, another broken recipe is the Redstone Block, but that works fine with just Malum+PL+QSL

**Comment by goldenapple3** [comment]
This has turned into a bit of a live chat but I have to go to bed now as it's very late here (and I'm not contributing much anyway at this point), good luck!

**Comment by RealRTTV** [comment]
found it, ill be releasing b1.0.7 in a bit

**Comment by gardenappl** [comment]
Awesome, thanks a lot!
